# ============> BASE (SHARED CONFIG) <================ #
spring:
  application:
    name: jobtrackr

  profiles:
    active: dev

server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    root: INFO
    com.jobtrackr: DEBUG